name: Joplin Continuous Integration for Appx
on: [push, pull_request]
jobs:
  pre_job:
    if: github.repository == 'laurent22/joplin'
    # Do not use unbuntu-latest because it causes `The operation was canceled` failures:
    # https://github.com/actions/runner-images/issues/6709
    runs-on: ubuntu-20.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'

  Main:
    needs: pre_job
    # We always process server or desktop release tags, because they also publish the release
    if: github.repository == 'ifurther/joplin' && (needs.pre_job.outputs.should_skip != 'true' || startsWith(github.ref, 'refs/tags/server-v') || startsWith(github.ref, 'refs/tags/v'))
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Do not use unbuntu-latest because it causes `The operation was canceled` failures:
        # https://github.com/actions/runner-images/issues/6709
        os: [windows-2022]
    steps:

      # Trying to fix random networking issues on Windows
      # https://github.com/actions/runner-images/issues/1187#issuecomment-686735760
      - name: Disable TCP/UDP offload on Windows
        if: runner.os == 'Windows'
        run: Disable-NetAdapterChecksumOffload -Name * -TcpIPv4 -UdpIPv4 -TcpIPv6 -UdpIPv6

      - uses: actions/checkout@v4
      - uses: olegtarasov/get-tag@v2.1.3
      - uses: actions/setup-node@v4
        with:
          # We need to pin the version to 18.15, because 18.16+ fails with this error:
          # https://github.com/facebook/react-native/issues/36440
          node-version: '18.15.0'
          cache: 'yarn'

      - name: Install Yarn
        run: |
          # https://yarnpkg.com/getting-started/install
          corepack enable

      # macos-latest ships with Python 3.12 by default, but this removes a
      # utility that's used by electron-builder (distutils) so we need to pin
      # Python to an earlier version.
      # Fixes error `ModuleNotFoundError: No module named 'distutils'`
      # Ref: https://github.com/nodejs/node-gyp/issues/2869
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build and publish Windows app
        if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v')
        env:
            CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CSC_KEY_PASSWORD }}
            CSC_LINK: ${{ secrets.WINDOWS_CSC_LINK }}
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
            IS_CONTINUOUS_INTEGRATION: 1
            BUILD_SEQUENCIAL: 1
        # To ensure that the operations stop on failure, all commands
        # should be on one line with "&&" in between.
        run: |
          yarn install
          cd packages/app-desktop
          yarn dist --arch x64 --target appx --publish=never
          yarn dist --arch ia32 --target appx --publish=never
          set npm_config_arch=arm64
          set npm_config_target_arch=arm64
          yarn dist --arm64 --target appx --publish=never